### ISSUE TITLE
Can I do this with your extension?

### ISSUE THREAD

**Issue by zydjohnHotmail** [mohamedmansour/reload-all-tabs-extension#30] opened 2021-03-10 20:47 UTC
Hello:
You found your extension, it is a good one.
I wounder if I can do this with your extension.
I have two web site: https://www.site1.com/ & https://www.site2.com/
I want to set the extension to automatically reload site1 every 20 seconds, 
and automatically site2 every minute.
But I have my own extensions running on those 2 sites, I want reload only affect the underlying DOM, not my extensions' content javascript.
Let me know if I can do this by changing some settings, like in manifest.json.
I want to use some fixed settings, so I don't have to manually reload them myself.
Please advise!

**Comment by leao-nardo** [comment] 2021-04-24 00:40
good idea , if you know how to do it then: make a fork of this > modify in your forked repo and then add a push here.
but try to make not "fixed settings" , make editable ones to be setted in the extension options page.
that way will be more useful  for you and for others.
ps. im not the dev here. i just found this git and have some mod ideas too.

**Comment by leao-nardo** [comment] 2021-04-24 01:08
also this looks like issue #10

**Comment by mohamedmansour** [comment] 2021-05-03 16:35
Hi @zydjohnHotmail , I think I have a feature bug tracking it as @leao-nardo stated (thank you)!  Lets discuss there Closing since it is duplicate.

Duplicate of #10

**Comment by mohamedmansour** [comment] 2021-05-03 16:35
Hi @zydjohnHotmail , I think I have a feature bug tracking it as @leao-nardo stated (thank you)!  Lets discuss there Closing since it is duplicate.

Duplicate of #10

**Closed by mohamedmansour** 2021-05-03 16:35 UTC
